const options = [
    
  { value: "ar", label: "Argentina" },
  { value: "au", label: "Australia" },
  { value: "at", label: "Austria" },
  { value: "be", label: "Belgium" },
  { value: "bg", label: "Bulgaria" },
  { value: "br", label: "Brazil" },
  { value: "ca", label: "Canada" },
  { value: "cl", label: "Chile" },
  { value: "co", label: "Colombia" },
  { value: "hr", label: "Croatia" },
  { value: "cy", label: "Cyprus" },
  { value: "cz", label: "Czech Republic" },
  { value: "dk", label: "Denmark" },
  { value: "de", label: "Germany" },
  { value: "ec", label: "Ecuador" },
  { value: "ee", label: "Estonia" },
  { value: "fi", label: "Finland" },
  { value: "fr", label: "France" },
  { value: "gr", label: "Greece" },
  { value: "hk", label: "Hong Kong" },
  { value: "hu", label: "Hungary" },
  { value: "id", label: "Indonesia" },
  { value: "ie", label: "Ireland" },
  { value: "il", label: "Israel" },
  { value: "in", label: "India" },
  { value: "is", label: "Iceland" },
  { value: "it", label: "Italy" },
  { value: "jp", label: "Japan" },
  { value: "lt", label: "Lithuania" },
  { value: "my", label: "Malaysia" },
  { value: "mx", label: "Mexico" },
  { value: "md", label: "Moldova" },
  { value: "nl", label: "Netherlands" },
  { value: "nz", label: "New Zealand" },
  { value: "no", label: "Norway" },
  { value: "mk", label: "North Macedonia" },
  { value: "pa", label: "Panama" },
  { value: "pe", label: "Peru" },
  { value: "ph", label: "Philippines" },
  { value: "pl", label: "Poland" },
  { value: "pt", label: "Portugal" },
  { value: "ro", label: "Romania" },
  { value: "ru", label: "Russia" },
  { value: "rs", label: "Serbia" },
  { value: "sg", label: "Singapore" },
  { value: "si", label: "Slovenia" },
  { value: "es", label: "Spain" },
  { value: "za", label: "South Africa" },
  { value: "kr", label: "South Korea" },
  { value: "se", label: "Sweden" },
  { value: "th", label: "Thailand" },
  { value: "tr", label: "Turkey" },
  { value: "ua", label: "Ukraine" },
  { value: "ae", label: "United Arab Emirates" },
  { value: "gb", label: "United Kingdom" },
  { value: "us", label: "United States" },
  { value: "vn", label: "Vietnam" }
 
];

export default options;
